#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) 1998 - 2020, Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.haxx.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
###########################################################################
language: c
os: linux
dist: bionic
cache:
  directories:
  - $HOME/wolfssl-4.4.0-stable
  - $HOME/mesalink-1.0.0
  - $HOME/nghttp2-1.39.2

env:
  global:
  - LD_LIBRARY_PATH=/usr/local/lib

addons:
  apt: &common_apt
    config:
      retries: true
    packages: &common_packages
    - cmake
    - valgrind
    - libev-dev
    - libc-ares-dev
    - g++-8
    - stunnel4
    - libidn2-dev
    - gnutls-bin
    - python-impacket

jobs:
  include:
  - env:
    - T=novalgrind NGTCP2=yes GNUTLS=yes C="PKG_CONFIG_PATH=$HOME/ngbuild --without-ssl --with-gnutls=$HOME/ngbuild --with-ngtcp2=$HOME/ngbuild --with-nghttp3=$HOME/ngbuild --enable-alt-svc" NOTESTS=
    - OVERRIDE_CC="CC=gcc-8" OVERRIDE_CXX="CXX=g++-8"
    addons:
      apt:
        <<: *common_apt
        packages:
        - *common_packages
        - libpsl-dev
        - libbrotli-dev
        - autogen
        - automake
        - autopoint
        - bison
        - gperf
        - libgmp-dev
        - libopts25-dev
        - libp11-kit-dev
        - libtasn1-6-dev
        - nettle-dev

before_install:
- export "${OVERRIDE_CC-blank=}"
- export "${OVERRIDE_CXX-blank=}"

install:
- if [ "$T" = "coverage" ]; then pip2 install --user cpp-coveralls; fi

# before_script and script:
# Travis isn't reliable catching errors in inline script commands (#3730).
# Do not add anything here, instead add to the respective script.
before_script:
- ./scripts/travis/before_script.sh || travis_terminate 1
script:
- if ! ./scripts/travis/script.sh; then echo 'BEGIN config.log'; cat config.log; travis_terminate 1; fi

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - /\/ci$/

notifications:
  email: false
